<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGHbDfz6\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGHbDfz6/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGHbDfz6.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGHbDfz6\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerGHbDfz6\Eccube_KernelProdContainer([
    'container.build_hash' => 'GHbDfz6',
    'container.build_id' => 'b077cfdf',
    'container.build_time' => 1726205720,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGHbDfz6');
